Repository microsoft/dicom-server, pull requests merged in 2023-05, with the labels that each got.

#2660 Fix Export E2E Test Cleanup
  build/ci/run-e2e-tests.yml
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExportTests.cs
Labels: Bug

#2659 Use Succeeded for Operation Status in V2
  src/Microsoft.Health.Dicom.Api.UnitTests/Controllers/OperationsControllerTests.cs
  src/Microsoft.Health.Dicom.Api/Controllers/OperationsController.cs
Labels: Bug, .NET

#2696 Fix Transient Export Test Failures
  build/ci/run-e2e-tests.yml
  src/Microsoft.Health.Dicom.Client/Models/ChangeFeedAction.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ExportTests.cs
Labels: Bug

#2698 Add e2e test to verify existing instance.
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Common/DicomInstancesManager.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Instance.cs
Labels: Test coverage

#2672 Use custom dicom implementation and version name
  src/Microsoft.Health.Dicom.Api/Registration/DicomServerServiceCollectionExtensions.cs
  src/Microsoft.Health.Dicom.Core.UnitTests/Features/FellowOak/CustomDicomImplementationTests.cs
  src/Microsoft.Health.Dicom.Core/Features/FellowOakDicom/CustomDicomImplementation.cs
  src/Microsoft.Health.Dicom.Functions/Registration/ServiceCollectionExtensions.cs
  src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomDatasetEqualityComparer.cs
  src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomFileEqualityComparer.cs
  src/Microsoft.Health.Dicom.Tests.Common/Comparers/DicomItemCollectionEqualityComparer.cs
  src/Microsoft.Health.Dicom.Tests.Common/Samples.cs
  test/Microsoft.Health.Dicom.Tests.Integration/Features/TranscoderTests.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/HttpIntegrationTestFixture.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Common.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Instance.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Series.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/RetrieveTransactionResourceTests.Study.cs
Labels: Feature

#2712 Keep Reading Change Feed Until Latest
  converter/dicom-cast/src/Microsoft.Health.DicomCast.Core.UnitTests/Features/Worker/ChangeFeedProcessorTests.cs
  converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/DicomWeb/Service/ChangeFeedRetrieveService.cs
  converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/DicomWeb/Service/IChangeFeedRetrieveService.cs
  converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/State/SyncState.cs
  converter/dicom-cast/src/Microsoft.Health.DicomCast.Core/Features/Worker/ChangeFeedProcessor.cs
Labels: Bug

#2742 Use Proper XUnit Test Collection Syntax
  src/Microsoft.Health.Dicom.Core.UnitTests/AutoValidationCollection.cs
  src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/StoreDatasetValidatorTestsV1.cs
  src/Microsoft.Health.Dicom.Core.UnitTests/Features/Store/StoreDatasetValidatorTestsV2.cs
  test/Microsoft.Health.Dicom.Tests.Integration/ChangeFeedCollection.cs
  test/Microsoft.Health.Dicom.Tests.Integration/Persistence/ChangeFeedTests.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/ChangeFeedCollection.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/ChangeFeedTests.cs
  test/Microsoft.Health.Dicom.Web.Tests.E2E/Rest/TemporalChangeFeedTests.cs
Labels: Bug
